### ISSUE TITLE
The foreign key values aren't populated in admin page when used with ReverseModelAdmin

### ISSUE THREAD

**Issue by maddiaks** [daniyalzade/django_reverse_admin#4] opened 2018-05-09 05:48 UTC

**Comment by daniyalzade** [comment] 2018-08-06 13:50
hey @maddiaks can you please give an example for this?

**Comment by daniyalzade** [comment] 2019-11-25 00:43
Closing this, because i cannot reproduce.

**Closed by daniyalzade** 2019-11-25 00:43 UTC
